# Generated by Django 4.1.3 on 2023-06-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
