# Generated by Django 4.1.3 on 2023-06-04 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_subevents_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='event',
            name='creators',
            field=models.ManyToManyField(related_name='creator_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
