# Generated by Django 4.1.3 on 2023-06-04 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_event_creator_event_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='creators',
            field=models.ManyToManyField(related_name='creator_subevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
