# Generated by Django 4.1.3 on 2023-06-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subevents_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subevents',
            name='creators',
        ),
    ]
